onEvent('block.tags', e => {
	// e.add('betterpunching:ignore_hurts_debuff', '#storagedrawers:drawers')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_barrel_1')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_barrel_2')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_barrel_3')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_barrel_4')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_iron_barrel_1')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_iron_barrel_2')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_iron_barrel_3')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_iron_barrel_4')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_gold_barrel_1')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_gold_barrel_2')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_gold_barrel_3')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_gold_barrel_4')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_diamond_barrel_1')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_diamond_barrel_2')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_diamond_barrel_3')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_diamond_barrel_4')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_netherite_barrel_1')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_netherite_barrel_2')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_netherite_barrel_3')
	e.add('betterpunching:ignore_hurts_debuff', 'sophisticatedstorage:limited_netherite_barrel_4')
	e.add('betterpunching:ignore_all', '#valhelsia_structures:big_jars')
	e.add('betterpunching:ignore_all', '#valhelsia_structures:jars')
	e.add('betterpunching:ignore_all', 'supplementaries:stick')
	e.add('betterpunching:ignore_all', '#create:toolboxes')
	e.add('betterpunching:ignore_all', '#chipped:lantern')
	e.add('betterpunching:ignore_all', '#chipped:special_lantern')
	e.add('betterpunching:ignore_all', 'doggytalents:dog_bed')
	e.add('betterpunching:ignore_all', 'minecraft:redstone_lamp')
	e.add('betterpunching:ignore_speed_debuff', '#domum_ornamentum:bricks')
})