
#Settings for world gen (Doesn't work in 1.18.2 and beyond. Use datapacks instead.)
["World Gen"]
	#Average chunk separation between companion houses
	#Range: > 11
	averageHouseSeparation = 20

["Companion config"]
	#Toggles friendly fire between companions
	friendlyFireCompanions = false
	#Toggles friendly fire between player and companion
	friendlyFirePlayer = false
	#Toggles fall damage for companions
	fallDamage = false
	#Toggles whether companions spawn with armor
	spawnArmor = true
	#Toggles whether companions spawn with a weapon
	spawnWeapon = true
	#Sets the base health of each companion. Companions spawn with up to +-4 from the base health
	#Range: > 5
	baseHealth = 20
	#Toggles whether companions ask for food if their health goes below half.
	lowHealthFood = true
	#Toggles whether companions alert you if a creeper is nearby.
	creeperWarning = true
	#Z@RYA = Список возможных требований. Формат: Предмет|Мин|Макс, например: minecraft:cooked_porkchop|5|30
	requirements = ["minecraft:iron_ingot|3|25", "create:precision_mechanism|1|2", "minecraft:cooked_chicken|4|18", "minecraft:apple|10|15", "minecraft:emerald|1|32", "minecraft:turtle_egg|1|2", "supplementaries:candy|8|64", "farmersdelight:cabbage_crate|3|8", "immersive_melodies:lute|1|1", "minecraft:gold_block|1|3", "minecraft:lapis_block|2|7", "minecraft:iron_block|2|4", "minecraft:copper_block|4|6", "minecraft:coal_block|5|10", "minecraft:bookshelf|3|12", "minecraft:sea_lantern|1|4", "minecraft:dried_kelp_block|3|9", "minecraft:skeleton_skull|3|6", "minecraft:charcoal|8|26", "minecraft:amethyst_shard|4|20", "minecraft:gold_ingot|6|18", "minecraft:mushroom_stew|4|8", "minecraft:cooked_porkchop|8|18", "minecraft:bread|8|25", "minecraft:golden_apple|1|4", "minecraft:leather|5|20", "minecraft:tropical_fish|4|8", "minecraft:cookie|16|64", "minecraft:cooked_beef|4|16", "minecraft:ender_pearl|1|8", "minecraft:golden_carrot|4|16", "create:sweet_roll|1|12"]
	#Z@RYA = Минимальное количество возможных требований
	#Range: > 1
	minRequirements = 2
	#Z@RYA = Максимальное количество возможных требований
	#Range: > 1
	maxRequirements = 5

