
[logbegone]
	phrases = ["So I'm inject there", "Registering S2C receiver with id", "Registering C2S receiver with id", "Registering vanilla category extensions:", "Registering recipe catalysts:", "Registering advanced plugins:", "Registering recipes transfer handlers:", "Registering gui handlers:", "Registering config factory for mod", "Exception loading blockstate definition: 'valhelsia_structures:", "PathResourcePack base class instantiated with root path of mod file", "Registering item subtypes:", "Registering fluid subtypes:", "Registering ingredients:", "Registering categories:", "Could not find a matching ingredient to remove: 1 block_bit chiselsandbits:block_bit"]
	regex = [""]

