
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = false
	#Message that displays when Teleport is blocked
	blockedmessage = "Портал сдерживает всех по ту и по эту сторону, сломайте %item% чтобы нарушить равновесие..."
	#Title for the Advancements
	craftedmessage = "%dim% Unlocked!"
	#Description for the Advancements
	description = "Obtain a %item%"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "warden_and_sculk:reinforced_deepslate,warden_and_sculk:reinforced_deepslate"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether,minecraft:the_end"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether,End"
	#Z@RYA = Отключает достижение из мода.
	disableAdvancement = true
	#Z@RYA = Игровое правило, которое блокирует смену измерения для любого существа.
	#Здесь устанавливается значение по умолчанию.
	disablePortal = true
	#Z@RYA = Заголовок базового достижения
	rootTitle = "Restricted Portals"
	#Z@RYA = Описание базового достижения
	rootDescription = "Craft items to Unlock Dimensions"

