[universal]
	delay = "200"
	fade_in = "100"
	fade_out = "100"

# =========================
# Меню
[main_menu_music]
	[main_menu_music.trigger]
		name = "menu"

[hom3_main_menu]
	[hom3_main_menu.trigger]
		name = "menu"

[rok_nardin_the_cad]
	[rok_nardin_the_cad.trigger]
		name = "menu"

[samuel_kim_kakyoin_theme]
	[samuel_kim_kakyoin_theme.trigger]
		name = "menu"

[samuel_kim_house_of_the_dragon_targaryen]
	[samuel_kim_house_of_the_dragon_targaryen.trigger]
		name = "menu"

[diggy_diggy_hole]
	[diggy_diggy_hole.trigger]
		name = "menu"

[halo_2_menu]
	[halo_2_menu.trigger]
		name = "menu"

[stalker_2_come_to_me]
	[stalker_2_come_to_me.trigger]
		name = "menu"
# =========================

# =========================
# Стандартная в верхнем мире
[bonebottom_silksong]
	[bonebottom_silksong.trigger]
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld_ambient"
		priority = "3"

[hollow_knight_city_of_tears]
	[hollow_knight_city_of_tears.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_crossroads]
	[hollow_knight_crossroads.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_crystal_peak]
	[hollow_knight_crystal_peak.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_dirtmouth]
	[hollow_knight_dirtmouth.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_enter_hallownest]
	[hollow_knight_enter_hallownest.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_fungal_wastes]
	[hollow_knight_fungal_wastes.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_greenpath]
	[hollow_knight_greenpath.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_hollow_knight]
	[hollow_knight_hollow_knight.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_queens_gardens]
	[hollow_knight_queens_gardens.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_reflection]
	[hollow_knight_reflection.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_resting_grounds]
	[hollow_knight_resting_grounds.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_the_white_lady]
	[hollow_knight_the_white_lady.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[hollow_knight_white_palace]
	[hollow_knight_white_palace.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[oversea_away]
	[oversea_away.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[oversea_exhale]
	[oversea_exhale.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[oversea_home]
	[oversea_home.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[ambient_pride]
	[ambient_pride.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[c418_sweden]
	[c418_sweden.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[c418_wet_hands]
	[c418_wet_hands.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[skyrim_secunda]
	[skyrim_secunda.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[minecraft_ambient_style]
	[minecraft_ambient_style.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[skyrim_the_streets_of_whiterun]
	[skyrim_the_streets_of_whiterun.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[howard_shore_the_shire]
	[howard_shore_the_shire.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[cat_trumpet_waltz_of_chihiro]
	[cat_trumpet_waltz_of_chihiro.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[cicada_over_coastal_range]
	[cicada_over_coastal_range.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[xenoblade_title]
	[xenoblade_title.trigger]
		name = "dimension"
		identifier = "overworld_ambient"

[yasunori_nishiki_octopath_traveler]
	[yasunori_nishiki_octopath_traveler.trigger]
		name = "dimension"
		identifier = "overworld_ambient"
# =========================

# =========================
# Смэрт
[serega_sad]
	play_once = "2"
	[serega_sad.trigger]
		name = "dead"
		fade_in = "20"
		delay = "40"
		fade_out = "20"
		priority = "6"
# =========================

# =========================
# Музыка на кровавую луну
[christophe_le_guen__the_evil_ghost]
	[christophe_le_guen__the_evil_ghost.trigger]
		name = "bloodmoon"

[rok_nardin_where_is_your_god_now]
	[rok_nardin_where_is_your_god_now.trigger]
		name = "bloodmoon"

[rok_nardin_the_mad_queen]
	[rok_nardin_the_mad_queen.trigger]
		name = "bloodmoon"
# =========================

# =========================
# Битвы с мобами
[mick_gordon_rip_and_tear]
	[mick_gordon_rip_and_tear.trigger]
		name = "mob"
		resource_name = "MOB"
		mob_targeting = "true"
		identifier = "common_battle"
		priority = "5"
		fade_in = "20"
		delay = "40"
		fade_out = "20"

[mick_gordon_at_dooms_gate_cut]
	[mick_gordon_at_dooms_gate_cut.trigger]
		name = "mob"
		identifier = "common_battle"

[mick_gordon_bfg_division_cut]
	[mick_gordon_bfg_division_cut.trigger]
		name = "mob"
		identifier = "common_battle"

[mick_gordon_harbinger_cut]
	[mick_gordon_harbinger_cut.trigger]
		name = "mob"
		identifier = "common_battle"

[mick_gordon_skullhacker_cut]
	[mick_gordon_skullhacker_cut.trigger]
		name = "mob"
		identifier = "common_battle"

[jojo_stardust_crusaders]
	[jojo_stardust_crusaders.trigger]
		name = "mob"
		identifier = "common_battle"

[naruto_battle_music]
	[naruto_battle_music.trigger]
		name = "mob"
		identifier = "common_battle"

[[mick_gordon_cultist_base]]
	[mick_gordon_cultist_base.trigger]
		name = "mob"
		identifier = "common_battle"

[kondrashov_hell_to_pay_instrumental_cut]
	[kondrashov_hell_to_pay_instrumental_cut.trigger]
		name = "mob"
		identifier = "common_battle"
# =========================

# =========================
# Битвы с боссами
[the_only_thing_they_fear_is_you]
	[the_only_thing_they_fear_is_you.trigger]
		name = "mob"
		resource_name = "BOSS"
		mob_targeting = "true"
		identifier = "boss_battle"
		priority = "9"
		fade_in = "20"
		delay = "20"
		fade_out = "20"

[jojo_theme_doom_version]
	[jojo_theme_doom_version.trigger]
		name = "mob"
		identifier = "boss_battle"

[carameii_puss_in_boots_deaths_theme]
	[carameii_puss_in_boots_deaths_theme.trigger]
		name = "mob"
		identifier = "boss_battle"

[dark_souls_manus]
	[dark_souls_manus.trigger]
		name = "mob"
		identifier = "boss_battle"

[dark_souls_3_vordt_of_the_boreal_valley_cut]
	[dark_souls_3_vordt_of_the_boreal_valley_cut.trigger]
		name = "mob"
		identifier = "boss_battle"

[dark_souls_artorias_of_the_abyss_kalameet]
	[dark_souls_artorias_of_the_abyss_kalameet.trigger]
		name = "mob"
		identifier = "boss_battle"

[mgr_it_has_to_be_this_way]
	[mgr_it_has_to_be_this_way.trigger]
		name = "mob"
		identifier = "boss_battle"
# =========================

# =========================
# В эндере
[cyberpunk_2077]
	[cyberpunk_2077.trigger]
		name = "dimension"
		resource_name = "end"
		identifier = "end_music"
		priority = "6"

[tokyo_machine_rock_it]
	[tokyo_machine_rock_it.trigger]
		name = "dimension"
		identifier = "end_music"

[van_halen_jump]
	[van_halen_jump.trigger]
		name = "dimension"
		identifier = "end_music"

[pacifica_music_hell_from_above]
	[pacifica_music_hell_from_above.trigger]
		name = "dimension"
		identifier = "end_music"

[infraction_chimera]
	[infraction_chimera.trigger]
		name = "dimension"
		identifier = "end_music"

[ghostrifter_compromised]
	[ghostrifter_compromised.trigger]
		name = "dimension"
		identifier = "end_music"
# =========================

# =========================
# В аду
[at_doom_gates]
	[at_doom_gates.trigger]
		name = "dimension"
		resource_name = "nether"
		identifier = "nether_ambient"
		priority = "6"

[disturbed_decadence]
	[disturbed_decadence.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[mick_gordon_doom_eternal_heavens_wrath]
	[mick_gordon_doom_eternal_heavens_wrath.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[hom3_necropolis_town]
	[hom3_necropolis_town.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[rok_nardin_the_mad_king]
	[rok_nardin_the_mad_king.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[rok_nardin_the_devil]
	[rok_nardin_the_devil.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[samuel_kim_diavolo_theme]
	[samuel_kim_diavolo_theme.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[ffdp_trouble_tribute_instrumental]
	[ffdp_trouble_tribute_instrumental.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[ffdp_indestructible_instrumental]
	[ffdp_indestructible_instrumental.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[ffdp_down_with_the_the_sickness_instrumental]
	[ffdp_down_with_the_the_sickness_instrumental.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[mick_gordon_hellwalker]
	[mick_gordon_hellwalker.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[mick_gordon_flesh_and_metal]
	[mick_gordon_flesh_and_metal.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[mick_gordon_the_icon_of_sin]
	[mick_gordon_the_icon_of_sin.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[[mick_gordon_cultist_base]]
	[mick_gordon_cultist_base.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[mick_gordon_metal_hell]
	[mick_gordon_metal_hell.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[dragonforce_through_the_fire_and_flames_instrumental]
	[dragonforce_through_the_fire_and_flames_instrumental.trigger]
		name = "dimension"
		identifier = "nether_ambient"

[kondrashov_hell_to_pay_instrumental]
	[kondrashov_hell_to_pay_instrumental.trigger]
		name = "dimension"
		identifier = "nether_ambient"
# =========================

# =========================
# Музыка ночью
[jojo_kiras_killer]
	[[jojo_kiras_killer.trigger]]
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld_night"
		priority = "4"
    [[jojo_kiras_killer.trigger]]
        name = "time"
        priority = "4"
        start = "night"
        end = "6"
        identifier = "nighttime"

[stranger_things_c418_remix]
	[[stranger_things_c418_remix.trigger]]
		name = "dimension"
		identifier = "overworld_night"
    [[stranger_things_c418_remix.trigger]]
        name = "time"
        identifier = "nighttime"

[skyrim_journeys_end]
	[[skyrim_journeys_end.trigger]]
		name = "dimension"
		identifier = "overworld_night"
    [[skyrim_journeys_end.trigger]]
        name = "time"
        identifier = "nighttime"

[skyrim_aurora]
	[[skyrim_aurora.trigger]]
		name = "dimension"
		identifier = "overworld_night"
    [[skyrim_aurora.trigger]]
        name = "time"
        identifier = "nighttime"

[liberty]
	[[liberty.trigger]]
		name = "dimension"
		identifier = "overworld_night"
    [[liberty.trigger]]
        name = "time"
        identifier = "nighttime"

[vespertine]
	[[vespertine.trigger]]
		name = "dimension"
		identifier = "overworld_night"
    [[vespertine.trigger]]
        name = "time"
        identifier = "nighttime"

[samuel_kim_edgerunners_i_really_want_to_stay_at_your_house]
	[[samuel_kim_edgerunners_i_really_want_to_stay_at_your_house.trigger]]
		name = "dimension"
		identifier = "overworld_night"
    [[samuel_kim_edgerunners_i_really_want_to_stay_at_your_house.trigger]]
        name = "time"
        identifier = "nighttime"

[toby_fox_undertale]
	[[toby_fox_undertale.trigger]]
		name = "dimension"
		identifier = "overworld_night"
    [[toby_fox_undertale.trigger]]
        name = "time"
        identifier = "nighttime"
# =========================

# =========================
# Музыка в пустыне
[jojo_torture_dance]
	[jojo_torture_dance.trigger]
		name = "biome"
		biome_category = "desert"
		identifier = "sands"
		priority = "3"

[hom3_rampart]
	[hom3_rampart.trigger]
		name = "biome"
		identifier = "sands"

[derek_fiechter_gates_of_arabia]
	[derek_fiechter_gates_of_arabia.trigger]
		name = "biome"
		identifier = "sands"

[derek_fiechter_desert_caravans]
	[derek_fiechter_desert_caravans.trigger]
		name = "biome"
		identifier = "sands"

[derek_fiechter_lost_city_of_the_sands]
	[derek_fiechter_lost_city_of_the_sands.trigger]
		name = "biome"
		identifier = "sands"
# =========================

# =========================
# Музыка в снегах
[stalker_guitar]
	[stalker_guitar.trigger]
		name = "biome"
		biome_category = "taiga"
		identifier = "taiga"
		priority = "3"

[skyrim_ancient_stones]
	[skyrim_ancient_stones.trigger]
		name = "biome"
		identifier = "taiga"

[skyrim_dawn]
	[skyrim_dawn.trigger]
		name = "biome"
		identifier = "taiga"

[winter_music_blackcoal_cottage]
	[winter_music_blackcoal_cottage.trigger]
		name = "biome"
		identifier = "taiga"

[spirits_of_our_dreams_shimmer_of_nightflies]
	[spirits_of_our_dreams_shimmer_of_nightflies.trigger]
		name = "biome"
		identifier = "taiga"

[rannar_sillad_observations_from_a_faraway_place]
	[rannar_sillad_observations_from_a_faraway_place.trigger]
		name = "biome"
		identifier = "taiga"

[rannar_sillad_hues]
	[rannar_sillad_hues.trigger]
		name = "biome"
		identifier = "taiga"

[rannar_sillard_summits]
	[rannar_sillard_summits.trigger]
		name = "biome"
		identifier = "taiga"
# =========================

# =========================
# Музыка в океане (по приоритету выше чем generic)
[pirates_of_the_caribbean_famous]
	[pirates_of_the_caribbean_famous.trigger]
		name = "biome"
		biome_category = "ocean"
		identifier = "ocean"
		priority = "4"

[black_flag_running_down_to_cuba]
	[black_flag_running_down_to_cuba.trigger]
		name = "biome"
		identifier = "ocean"

[black_flag_william_taylor]
	[black_flag_william_taylor.trigger]
		name = "biome"
		identifier = "ocean"

[irish_rovers_drunken_sailer]
	[irish_rovers_drunken_sailer.trigger]
		name = "biome"
		identifier = "ocean"

[samuel_kim_one_piece_mashup_pirates_of_the_caribbean]
	[samuel_kim_one_piece_mashup_pirates_of_the_caribbean.trigger]
		name = "biome"
		identifier = "ocean"

[orchestral_wellerman]
	[orchestral_wellerman.trigger]
		name = "biome"
		identifier = "ocean"

[irish_rovers_the_jolly_roving_tar]
	[irish_rovers_the_jolly_roving_tar.trigger]
		name = "biome"
		identifier = "ocean"

[irish_rovers_whiskey_in_the_jar]
	[irish_rovers_whiskey_in_the_jar.trigger]
		name = "biome"
		identifier = "ocean"

[skullduggers_bully_in_the_alley]
	[skullduggers_bully_in_the_alley.trigger]
		name = "biome"
		identifier = "ocean"

[game_of_thrones_main_title]
	[game_of_thrones_main_title.trigger]
		name = "biome"
		identifier = "ocean"

[secret_garden_elan]
	[secret_garden_elan.trigger]
		name = "biome"
		identifier = "ocean"

[robin_beanland_adventure_awaits]
	[robin_beanland_adventure_awaits.trigger]
		name = "biome"
		identifier = "ocean"

[robin_beanland_on_the_warpath]
	[robin_beanland_on_the_warpath.trigger]
		name = "biome"
		identifier = "ocean"

[robin_beanland_bosun_bill]
	[robin_beanland_bosun_bill.trigger]
		name = "biome"
		identifier = "ocean"

[robin_beanland_maiden_voyage]
	[robin_beanland_maiden_voyage.trigger]
		name = "biome"
		identifier = "ocean"

[assasins_creed_fish_in_the_sea]
	[assasins_creed_fish_in_the_sea.trigger]
		name = "biome"
		identifier = "ocean"
# =========================