# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding the main config file

[triggers]
	[triggers.height]
		priority = "5"
		level = "1"
		identifier = "underground"
	[[triggers.biome]]
		priority = "4"
		biome_category = [ "ocean" ]
		identifier = "ocean"
	[[triggers.biome]]
		priority = "4"
		biome_category = [ "taiga" ]
		identifier = "taiga"
	[[triggers.biome]]
		priority = "4"
		biome_category = [ "desert" ]
		identifier = "sands"
	[triggers.time]
		song_delay = "600"
		priority = "3"
		time_bundle = "night"
		identifier = "nighttime"
	[triggers.bloodmoon]
		priority = "7"
	[[triggers.mob]]
		detection_range = "50"
		fade_out = "20"
		identifier = "boss_battle"
		priority = "8"
		fade_in = "20"
		trigger_delay = "20"
		mob_targeting = false
		resource_name = [ "BOSS" ]
	[[triggers.dimension]]
		priority = "6"
		resource_name = [ "nether" ]
		identifier = "nether_ambient"
	[[triggers.dimension]]
		priority = "6"
		resource_name = [ "end" ]
		identifier = "end_music"
	[[triggers.mob]]
		fade_out = "20"
		identifier = "common_battle"
		priority = "5"
		fade_in = "20"
		resource_name = [ "MOB" ]
	[triggers.dead]
		priority = "9"
		fade_in = "20"
		trigger_delay = "20"
		fade_out = "20"
	[[triggers.dimension]]
		identifier = "overworld_ambient"
		priority = "2"
		resource_name = [ "overworld" ]
		song_delay = "600"
	[triggers.universal]
		fade_out = "40"
		fade_in = "100"
	[triggers.menu]
[songs]
	[songs.epikus_otar_the_foul]
		triggers = [ "dimension-end_music" ]
	[songs.alibi_armageddon]
		triggers = [ "dimension-end_music" ]
	[songs.oleg_semenov_dark_angel]
		triggers = [ "menu" ]
	[songs.tom_player_axis]
		triggers = [ "height-underground" "dimension-overworld_ambient" ]
	[songs.red_moth_darkness_below]
		triggers = [ "mob-boss_battle" ]
	[songs.ashley_serena_lullaby_of_woe]
		triggers = [ "height-underground" "dimension-overworld_ambient" ]
	[songs.peter_gundry_a_grave_conversation]
		triggers = [ "height-underground" "dimension-overworld_ambient" ]
	[songs.suno_aimusiclounge_lofi_chillout_v2]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.suno_dmgmedia_ashes]
		triggers = [ "biome-taiga" ]
	[songs.suno_zarya_prepare_to_die]
		triggers = [ "menu" ]
	[songs.suno_iroot_cello]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.suno_tarsit_rastar]
		triggers = [ "biome-sands" ]
	[songs.suno_lounge_radio]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.suno_kant_bridge]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.suno_aerial_awakening]
		triggers = [ "biome-ocean" ]
	[songs.suno_wanderlust]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.suno_a_knights_calm]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.shibayanrecords_tiny_little_adiantum]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.diggy_diggy_hole]
		triggers = [ "height-underground" "dimension-overworld_ambient" ]
	[songs.assasins_creed_fish_in_the_sea]
		triggers = [ "biome-ocean" ]
	[songs.robin_beanland_maiden_voyage]
		triggers = [ "biome-ocean" ]
	[songs.robin_beanland_bosun_bill]
		triggers = [ "biome-ocean" ]
	[songs.robin_beanland_on_the_warpath]
		triggers = [ "biome-ocean" ]
	[songs.robin_beanland_adventure_awaits]
		triggers = [ "biome-ocean" ]
	[songs.secret_garden_elan]
		triggers = [ "biome-ocean" ]
	[songs.game_of_thrones_main_title]
		triggers = [ "biome-ocean" ]
	[songs.skullduggers_bully_in_the_alley]
		triggers = [ "biome-ocean" ]
	[songs.irish_rovers_whiskey_in_the_jar]
		triggers = [ "biome-ocean" ]
	[songs.irish_rovers_the_jolly_roving_tar]
		triggers = [ "biome-ocean" ]
	[songs.orchestral_wellerman]
		triggers = [ "biome-ocean" ]
	[songs.samuel_kim_one_piece_mashup_pirates_of_the_caribbean]
		triggers = [ "biome-ocean" ]
	[songs.irish_rovers_drunken_sailer]
		triggers = [ "biome-ocean" ]
	[songs.black_flag_william_taylor]
		triggers = [ "biome-ocean" ]
	[songs.black_flag_running_down_to_cuba]
		triggers = [ "biome-ocean" ]
	[songs.pirates_of_the_caribbean_famous]
		triggers = [ "biome-ocean" ]
	[songs.rannar_sillard_summits]
		triggers = [ "biome-taiga" ]
	[songs.rannar_sillad_hues]
		triggers = [ "biome-taiga" ]
	[songs.rannar_sillad_observations_from_a_faraway_place]
		triggers = [ "biome-taiga" ]
	[songs.spirits_of_our_dreams_shimmer_of_nightflies]
		triggers = [ "biome-taiga" ]
	[songs.winter_music_blackcoal_cottage]
		triggers = [ "biome-taiga" ]
	[songs.skyrim_dawn]
		triggers = [ "biome-taiga" ]
	[songs.skyrim_ancient_stones]
		triggers = [ "biome-taiga" ]
	[songs.stalker_guitar]
		triggers = [ "biome-taiga" ]
	[songs.derek_fiechter_lost_city_of_the_sands]
		triggers = [ "biome-sands" ]
	[songs.derek_fiechter_desert_caravans]
		triggers = [ "biome-sands" ]
	[songs.derek_fiechter_gates_of_arabia]
		triggers = [ "biome-sands" ]
	[songs.hom3_rampart]
		triggers = [ "biome-sands" ]
	[songs.jojo_torture_dance]
		triggers = [ "biome-sands" ]
	[songs.toby_fox_undertale]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.samuel_kim_edgerunners_i_really_want_to_stay_at_your_house]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.vespertine]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.liberty]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.skyrim_aurora]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.skyrim_journeys_end]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.stranger_things_c418_remix]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.jojo_kiras_killer]
		triggers = [ "time-nighttime" "dimension-overworld_ambient" ]
	[songs.kondrashov_hell_to_pay_instrumental]
		triggers = [ "dimension-nether_ambient" ]
	[songs.dragonforce_through_the_fire_and_flames_instrumental]
		triggers = [ "dimension-nether_ambient" ]
	[songs.mick_gordon_metal_hell]
		triggers = [ "dimension-nether_ambient" ]
	[[songs.mick_gordon_cultist_base]]
		triggers = [ "dimension-nether_ambient" ]
	[songs.mick_gordon_the_icon_of_sin]
		triggers = [ "dimension-nether_ambient" ]
	[songs.mick_gordon_flesh_and_metal]
		triggers = [ "dimension-nether_ambient" ]
	[songs.mick_gordon_hellwalker]
		triggers = [ "dimension-nether_ambient" ]
	[songs.ffdp_down_with_the_the_sickness_instrumental]
		triggers = [ "dimension-nether_ambient" ]
	[songs.ffdp_indestructible_instrumental]
		triggers = [ "dimension-nether_ambient" ]
	[songs.ffdp_trouble_tribute_instrumental]
		triggers = [ "dimension-nether_ambient" ]
	[songs.samuel_kim_diavolo_theme]
		triggers = [ "dimension-nether_ambient" ]
	[songs.rok_nardin_the_devil]
		triggers = [ "dimension-nether_ambient" ]
	[songs.rok_nardin_the_mad_king]
		triggers = [ "dimension-nether_ambient" ]
	[songs.hom3_necropolis_town]
		triggers = [ "dimension-nether_ambient" ]
	[songs.mick_gordon_doom_eternal_heavens_wrath]
		triggers = [ "dimension-nether_ambient" ]
	[songs.disturbed_decadence]
		triggers = [ "dimension-nether_ambient" ]
	[songs.at_doom_gates]
		triggers = [ "dimension-nether_ambient" ]
	[songs.ghostrifter_compromised]
		triggers = [ "dimension-end_music" ]
	[songs.infraction_chimera]
		triggers = [ "dimension-end_music" ]
	[songs.pacifica_music_hell_from_above]
		triggers = [ "dimension-end_music" ]
	[songs.van_halen_jump]
		triggers = [ "dimension-end_music" ]
	[songs.tokyo_machine_rock_it]
		triggers = [ "dimension-end_music" ]
	[songs.cyberpunk_2077]
		triggers = [ "dimension-end_music" ]
	[songs.mgr_it_has_to_be_this_way]
		triggers = [ "mob-boss_battle" ]
	[songs.dark_souls_artorias_of_the_abyss_kalameet]
		triggers = [ "mob-boss_battle" ]
	[songs.dark_souls_3_vordt_of_the_boreal_valley_cut]
		triggers = [ "mob-boss_battle" ]
	[songs.dark_souls_manus]
		triggers = [ "mob-boss_battle" ]
	[songs.carameii_puss_in_boots_deaths_theme]
		triggers = [ "mob-boss_battle" ]
	[songs.jojo_theme_doom_version]
		triggers = [ "mob-boss_battle" ]
	[songs.the_only_thing_they_fear_is_you]
		triggers = [ "mob-boss_battle" ]
	[songs.kondrashov_hell_to_pay_instrumental_cut]
		triggers = [ "mob-common_battle" ]
	[[songs.mick_gordon_cultist_base]]
		triggers = [ "mob-common_battle" ]
	[songs.naruto_battle_music]
		triggers = [ "mob-common_battle" ]
	[songs.jojo_stardust_crusaders]
		triggers = [ "mob-common_battle" ]
	[songs.mick_gordon_skullhacker_cut]
		triggers = [ "mob-common_battle" ]
	[songs.mick_gordon_harbinger_cut]
		triggers = [ "mob-common_battle" ]
	[songs.mick_gordon_bfg_division_cut]
		triggers = [ "mob-common_battle" ]
	[songs.mick_gordon_at_dooms_gate_cut]
		triggers = [ "mob-common_battle" ]
	[songs.mick_gordon_rip_and_tear]
		triggers = [ "mob-common_battle" ]
	[songs.rok_nardin_the_mad_queen]
		triggers = [ "bloodmoon" ]
	[songs.rok_nardin_where_is_your_god_now]
		triggers = [ "bloodmoon" ]
	[songs.christophe_le_guen__the_evil_ghost]
		triggers = [ "bloodmoon" ]
	[songs.serega_sad]
		play_once = "2"
		triggers = [ "dead" ]
	[songs.yasunori_nishiki_octopath_traveler]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.xenoblade_title]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.cicada_over_coastal_range]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.cat_trumpet_waltz_of_chihiro]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.howard_shore_the_shire]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.skyrim_the_streets_of_whiterun]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.minecraft_ambient_style]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.skyrim_secunda]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.c418_wet_hands]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.c418_sweden]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.ambient_pride]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.oversea_home]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.oversea_exhale]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.oversea_away]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_the_white_lady]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_resting_grounds]
		triggers = [ "height-underground" "dimension-overworld_ambient" ]
	[songs.hollow_knight_reflection]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_queens_gardens]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_hollow_knight]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_greenpath]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_fungal_wastes]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_enter_hallownest]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_dirtmouth]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_crystal_peak]
		triggers = [ "dimension-overworld_ambient" ]
	[songs.hollow_knight_crossroads]
		triggers = [ "height-underground" "dimension-overworld_ambient" ]
	[songs.bonebottom_silksong]
		triggers = [ "height-underground" "dimension-overworld_ambient" ]
	[songs.stalker_2_come_to_me]
		triggers = [ "menu" ]
	[songs.halo_2_menu]
		triggers = [ "menu" ]
	[songs.samuel_kim_house_of_the_dragon_targaryen]
		triggers = [ "menu" ]
	[songs.samuel_kim_kakyoin_theme]
		triggers = [ "menu" ]
	[songs.rok_nardin_the_cad]
		triggers = [ "menu" ]
	[songs.hom3_main_menu]
		triggers = [ "menu" ]
	[songs.universal]
	[songs.main_menu_music]
		triggers = [ "menu" ]
