
#Settings related to gameplay
[gameplay]
	#If all progress should be lost on death
	resetOnDeath = true
	#Define the amount of XP refunded when decreasing skill level
	#Range: 0.0 ~ 1.0
	xpRefundFactor = 0.75
	#If right-click harvesting should be enabled.
	rightClickHarvest = false

