
["Welcome to the Better Punching mod server configuration file"]
	#Set how much damage should the player take from the Splinter effect
	#Range: 0.0 ~ 3.4028234663852886E38
	splinterDamage = 0.5
	#Set how much damage should the player take from punching the wrong block.
	#Range: 0.0 ~ 3.4028234663852886E38
	invalidPunchDamage = 0.5
	#Set how long should the Splinter effect last in seconds
	#Range: 0 ~ 1000000
	splinterDuration = 1
	#Set how long should the Bleeding effect last in seconds
	#Range: 0 ~ 1000000
	bleedingDuration = 3
	#Set how long should the Weakness effect last in seconds
	#Range: 0 ~ 1000000
	weaknessDuration = 4
	#Set how long should the Mining Fatigue effect last in seconds
	#Range: 0 ~ 1000000
	miningFatigueDuration = 4
