
[server]
	#Set to true to automatically use sleeping bags when placed
	autoUse = false
	#List of debuffs to apply to players after using the sleeping bag
	#Format: [effect] [duration(secs)] [power]
	sleepingBagDebuffs = ["minecraft:weakness 25 1", "minecraft:slowness 25 1", "minecraft:mining_fatigue 25 1"]

