
#Here you can disable talents.
#Notice that players with admin privileges can bypass this.
[Talents]
	"doggytalents:pack_puppy" = false
	"doggytalents:doggy_torch" = false
	"doggytalents:wolf_mount" = false
	"doggytalents:swimmer_dog" = false

