
["Dog Constants"]
	#Option to disable friendly fire for all players toward all dogs.
	#This is used to always be the case with friendly fire disabled for a single dog.
	all_player_cannot_attack_dog = true
	#When enabled, dogs cannot be killed by any means (except creative-mode-bypass damage,
	#in that case, you can still respawn your dog using his linked bed or commands).
	#Instead, when his health reaches Zero, he will go into Incapacitated Mode.
	immortal_dogs = false

