
[stamina]

	[stamina.skills]

		[stamina.skills.block]
			#Range: 0.0 ~ 10.0
			block_stamina_multiplier = 5.5

		[stamina.skills.dodge]
			#Range: 0 ~ 100
			roll_stamina_cost = 15
			#Range: 0 ~ 100
			step_stamina_cost = 12

		[stamina.skills.parry]
			#How much stamina will be drained on a failed parry.
			#Make the same as block_stamina_multiplier for no penalty.
			#Range: 0.0 ~ 10.0
			parry_penalty_multiplier = 5.5

	[stamina.weapons]

		[stamina.weapons.fixed_cost]
			#Range: 0 ~ 100
			staff_stamina_multiplier = 15