[stamina]
	#Actions other than paragliding or ascending will consume stamina.
	runningAndSwimmingConsumesStamina = true

	[stamina.consumptions]
		#Range: > -2147483648
		idleStaminaConsumption = 25
		#Range: > -2147483648
		runningStaminaConsumption = -8
		#Range: > -2147483648
		swimmingStaminaConsumption = -5
		#Range: > -2147483648
		underwaterStaminaConsumption = 6
		#Range: > -2147483648
		breathingUnderwaterStaminaConsumption = 14

