
#Server Settings
[server]
	#List of items that are not allowed to be put in backpacks - e.g. "minecraft:shulker_box"
	disallowedItems = ["supplementaries:sack","supplementaries:safe","minecraft:shulker_box", "minecraft:bundle", "create:white_toolbox", "create:orange_toolbox", "create:magenta_toolbox", "create:light_blue_toolbox", "create:yellow_toolbox", "create:lime_toolbox", "create:pink_toolbox", "create:gray_toolbox", "create:light_gray_toolbox", "create:black_toolbox", "create:red_toolbox", "create:green_toolbox", "create:brown_toolbox", "create:blue_toolbox", "create:purple_toolbox", "create:cyan_toolbox"]

	#Settings for Spawning Entities with Backpack
	[server.entityBackpackAdditions]
		#Turns on/off a chance that the entity that wears backpack gets jukebox upgrade and plays a music disc.
		playJukebox = false

	[server.nerfs]
		#Determines if too many backpacks in player's inventory cause slowness to the player
		tooManyBackpacksSlowness = true
		#Maximum number of backpacks in player's inventory that will not cause slowness
		#Range: 1 ~ 27
		maxNumberOfBackpacks = 2
