
#Server Settings
[server]
	#List of items that are not allowed to be put in backpacks - e.g. "minecraft:shulker_box"
	disallowedItems = ["supplementaries:sack","supplementaries:safe","minecraft:shulker_box", "create:white_toolbox", "create:orange_toolbox", "create:magenta_toolbox", "create:light_blue_toolbox", "create:yellow_toolbox", "create:lime_toolbox", "create:pink_toolbox", "create:gray_toolbox", "create:light_gray_toolbox", "create:black_toolbox", "create:red_toolbox", "create:green_toolbox", "create:brown_toolbox", "create:blue_toolbox", "create:purple_toolbox", "create:cyan_toolbox"]
	#Determines whether player can right click on backpack that another player is wearing to open it. If off will turn off that capability for everyone and remove related settings from backpack.
	allowOpeningOtherPlayerBackpacks = false

	#Settings for Spawning Entities with Backpack
	[server.entityBackpackAdditions]
		#Turns on/off a chance that the entity that wears backpack gets jukebox upgrade and plays a music disc.
		playJukebox = false
		#Map of entities that can spawn with backpack and related loot tables (if adding a loot is enabled) in format of "EntityRegistryName|LootTableName"
		entityLootTableList = ["minecraft:creeper|minecraft:chests/desert_pyramid", "minecraft:drowned|minecraft:chests/shipwreck_treasure", "wrd:ender_miner|minecraft:chests/end_city_treasure", "minecraft:evoker|minecraft:chests/woodland_mansion", "minecraft:husk|minecraft:chests/desert_pyramid", "minecraft:piglin|minecraft:chests/bastion_bridge", "minecraft:piglin_brute|minecraft:chests/bastion_treasure", "minecraft:pillager|minecraft:chests/pillager_outpost", "minecraft:skeleton|minecraft:chests/simple_dungeon", "minecraft:stray|minecraft:chests/igloo_chest", "minecraft:vex|minecraft:chests/woodland_mansion", "minecraft:vindicator|minecraft:chests/woodland_mansion", "minecraft:witch|minecraft:chests/buried_treasure", "minecraft:wither_skeleton|minecraft:chests/nether_bridge", "minecraft:zombie|minecraft:chests/simple_dungeon", "minecraft:zombie_villager|minecraft:chests/village/village_armorer", "minecraft:zombified_piglin|minecraft:chests/bastion_other"]

	[server.nerfs]
		#Determines if too many backpacks in player's inventory cause slowness to the player
		tooManyBackpacksSlowness = true
		#Maximum number of backpacks in player's inventory that will not cause slowness
		#Range: 1 ~ 27
		maxNumberOfBackpacks = 3

	#Tank Upgrade Settings
	[server.tankUpgrade]
		#How much FE can be transfered in / out per operation. This is a base transfer rate and same as max capacity gets multiplied by number of rows in storage and stack multiplier.
		#Range: 1 ~ 1000
		maxInputOutput = 200